# -*- coding:utf-8 -*-
'''
Created on 2017��8��31��

@author: onewalnut
'''
class tableParameter:
    virtualIdentityTableName = "T_VIRTUAL_IDENTITY"
    terminalFeatureTableName ="T_TERMINAL_FEATURE"
    collectionHotspotTableName =    "T_COLLECTION_HOTSPOT"    
    apEpAssociatedTableName = "T_AP_EP_ASSOCIATED"
    passengerStatisticsTableName = "T_PASSENGER_STATISTICS"
    passengerIntoStoreTableName = "T_PASSENGER_INTO_STORE"
    passengerNewOldTableName = "T_PASSENGER_NEW_OLD" 
    passengerOldTableName = "T_PASSENGER_OLD"
    
    
    virtualIdentityColumnParameter = " F_ID,F_LOCATION_ID,F_DEVICE_CODE,F_CLIENT_MAC,F_IMSI,F_IMEI,F_TEL,F_WEIXIN,F_TAOBAO,F_EMAIL,F_QQ,F_QQ_HISTORY,F_AREA_CODE,F_ORG_CODE,F_ILLEGAL_APP,F_BAIDU_ID,F_JINGDONG_ID,F_TENCENT_WB_ID,F_SINA_ID,F_YOUKU_ID,F_MILIAO_ID,F_XIECHENG_ID,F_DIDI_ID,F_MONO_ID,F_DANGDANG_ID,F_MEITUAN_ID,F_DAZHONG_ID,F_KUGOU_ID,F_CAP_TIME"
    
    terminalFeatureColumnParameter ="F_ID,F_LOCATION_ID,F_CAP_TIME,F_MAC,F_MAC_TYPE,F_SIGNAL,F_TERMINAL_SSID_LIST,F_ID_TYPE,F_ID_CONTENT,F_ACCESS_SSID,F_ACCESS_CHANNEL,F_DEVICE_MAC,F_DEVICE_CODE,F_HOTSPOT_ENCRYPTION_TYPE,F_X,F_Y,F_SITE_CODE,F_LONGITUDE,F_LATITUDE,F_HAS_FULLINDEX,F_AREA_CODE,F_ORG_CODE"
     
    collectionHotspotColumnParameter ="F_ID,F_HOTSPOT_MAC,F_HOTSPOT_SSID,F_HOTSPOT_CHANNEL,F_HOTSPOT_ENCRYPTION_TYPE,F_CAP_TIME,F_SIGNAL,F_X,F_Y,F_SITE_CODE,F_DEVICE_CODE,F_LOCATION_ID,F_LONGITUDE,F_LATITUDE,F_HAS_FULLINDEX,F_AREA_CODE,F_ORG_CODE"        
    
    apEpAssociatedColumnParameter = "ASSOCIATED_ID,TIMESTAP,DEVICE_MAC,DEVICE_CODE,AP_MAC,AP_SSID,EP_MACS"
    
    passengerStatisticsColumnParameter = "F_SITE_CODE,F_DEVICE_CODE,F_DEVICE_MAC,F_DATE,F_TIME,F_NUMBER,F_MACS,F_CREATE_TIME"
    
    passengerIntoStoreColumnParameter = "F_SITE_CODE,F_DEVICE_MAC,F_DEVICE_CODE,F_DATE,F_TIME,F_NUMBER,F_MACS,F_CREATE_TIME"
    
    passengerNewOldColumnParameter = "F_SITE_CODE,F_DATE,F_NEW_NUMBER,F_OLD_NUMBER,F_NEW_MACS,F_OLD_MACS,F_TIME,F_CREATE_TIME"
    
    passengerOldColumnParameter = "F_SITE_CODE,F_SITE_NAME,F_PASSENGER_NUMBER,F_PASSENGER_MACS,F_OLD_PERIOD,F_UPDATE_TIME"
    
